### ISSUE TITLE
I don't see any results on Windows

### ISSUE THREAD

**Issue by jeff9315** [esentis/flutter-find-unused-assets-and-dart-files#1]
I tried running this in my Flutter project and don't see any results in the Output panel. Does this do a static analysis of my code and display the results there? Am I missing something?

I know I have a few unused files and even an used folder.

**Comment by esentis** [comment]
Hello there ! Thanks for opening the issue, the plugin doesn't do a static analysis rather than it searches for any unreferenced `dart` files inside the `lib` folder of your project, and unreferenced assets from the `assets` folder. 

Normally, the results are in the `output` tab inside VS Code.

Can you show the project's folder hierarchy ?

**Comment by jeff9315** [comment]
Here's the hierarchy. All the files named _unused or OLD_ should show up in the output as being unused.

![image](https://github.com/esentis/flutter-find-unused-assets-and-dart-files/assets/20246623/29571e09-2309-401b-971f-4e623908d4ee)

**Comment by esentis** [comment]
Is the project open source so I could check it ?

**Comment by jeff9315** [comment]
I've never looked at the Output tab before ... but when I change it to **Window**, I see these messages. Probably because my project is on the L Drive. So I think one command would be `L:` and the next command would be the `cd` command

```
2023-09-02 09:17:36.204 [error] [Extension Host] exec error: Error: Command failed: cd "l:\FlutterApps\CERT\cert_starter_project" && 
      find "l:\FlutterApps\CERT\cert_starter_project/assets/" -type f ! -name "*.ttf" ! -name "*.otf" -print0 | while read -d $'\0' file; do
        name="$(basename "$file")"
        grep -rn -F -q "$name" "l:\FlutterApps\CERT\cert_starter_project/lib/"
        if [ $? -ne 0 ]; then
          echo "Unreferenced asset: $file"
        fi
      done
      
The syntax of the command is incorrect.

2023-09-02 09:17:36.205 [error] [Extension Host] exec error: Error: Command failed: cd "l:\FlutterApps\CERT\cert_starter_project" && 
      find lib/ -name "*.dart" -print0 | while read -d $'\0' file; do
        name="$(basename "$file")"
        grep -rn -F -q "$name" lib/
        if [ $? -ne 0 ]; then
          echo "Unreferenced file: $file"
        fi
      done
      
The syntax of the command is incorrect.

2023-09-02 09:17:36.206 [error] [Extension Host] exec error: Error: Command failed: cd "l:\FlutterApps\CERT\cert_starter_project" && 
      # Define the path to the pubspec.yaml file
      pubspec_file="./pubspec.yaml"
      
      # Extract the dependencies section
      deps_section=$(sed -n '/^dependencies:/,/^[^[:space:]]/p' "$pubspec_file")
      
      # Extract the dependencies
      deps=$(echo "$deps_section" | grep -Eo '^  [a-zA-Z0-9_-]+: .*$' | awk '{print $1}' | sed 's/://g')
    

      # Assign the number of dependencies to a variable
      dep_count=$(echo "$deps" | wc -w | xargs)
      
      # Echo the number of dependencies
      echo "$dep_count dependencies found"

      for dep in $deps; do
          count=$(grep -R "import.*$dep" lib/ | wc -l)
          if [ $count -eq 0 ]; then
              echo "Unreferenced dependency: $dep"
          fi
      done
      
The syntax of the command is incorrect.
```

**Comment by jeff9315** [comment]
No, it's not Open Source. It's just on my own PC at this time. But I think the L drive is the key.

**Comment by esentis** [comment]
Besides the project being on external drive, seems like it uses both direction backslash when trying to find the `assets` :

`find l:\FlutterApps\CERT\cert_starter_project/assets/"`

**Comment by jeff9315** [comment]
Hopefully, that's an easy fix for you. BTW, it's not an external drive ... just a separate partition on my main drive so that I can keep my Windows OS and installed programs separate from everything else.

**Comment by esentis** [comment]
Thanks for the report ! I think I know how to fix it, will update as soon as possible.

**Comment by jeff9315** [comment]
Any update on this? This looks like it's exactly what I've been hoping for!

Thanks ... Jeff

**Comment by esentis** [comment]
Hello @jeff9315 , I didn't had much free time. I will try get it done this weekend. Seems the issue is more complicated than I thought and I need to test it on a Windows machine.

**Comment by esentis** [comment]
@jeff9315 Update the extension, everything should be working as expected.

**Comment by jeff9315** [comment]
Perfect!! Exactly what I needed. I thought I only had 4 or 5 unused files. But your extension found a LOT.
